In [1]:
import numpy as np

# DataTypes & Attribute

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],
               [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a3 = np.array([[[1,2,3,3.1],
                [4,5,6,6.1],
                [7,8,9,9.1]],
               [[10,11,12,12.1],
                [13,14,15,15.1],
                [16,17,18,18.1]]
              ])
a3

array([[[ 1. ,  2. ,  3. ,  3.1],
        [ 4. ,  5. ,  6. ,  6.1],
        [ 7. ,  8. ,  9. ,  9.1]],

       [[10. , 11. , 12. , 12.1],
        [13. , 14. , 15. , 15.1],
        [16. , 17. , 18. , 18.1]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 4)

In [9]:
#  function return the number of dimensions of an array
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('float64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 24)

# Create a DataFrame from Numpy array

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# Creating arrays

In [14]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int32')

In [16]:
ones = np.ones((2,3)) #Return a new array of given shape and type, filled with ones.
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
zeros = np.zeros((2,3)) #Return a new array of given shape and type, filled with zeros.
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[3, 8, 4, 3, 7],
       [0, 8, 0, 5, 7],
       [2, 0, 4, 2, 7]])

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [23]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.38813438, 0.15876423, 0.24876922],
       [0.68389596, 0.61960804, 0.47151382],
       [0.40462181, 0.59501805, 0.3114724 ],
       [0.52294459, 0.02380214, 0.90004407],
       [0.10503295, 0.46218152, 0.1315207 ]])

In [24]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.98752214, 0.98768117, 0.57061694],
       [0.52556958, 0.73484652, 0.99407787],
       [0.23888016, 0.10523441, 0.09418297],
       [0.06715272, 0.32787567, 0.13721843],
       [0.04923427, 0.13530267, 0.21774207]])

# Random seed

In [26]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(0,10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

# np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

In [36]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.72816128, 0.82122761, 0.76051512],
       [0.00714328, 0.42025683, 0.46313622],
       [0.0554995 , 0.54144213, 0.60777075],
       [0.82845319, 0.94180927, 0.12814785],
       [0.23043067, 0.6591584 , 0.13247399]])

# Viewing arrays and metrics

In [39]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [38]:
## Find unique
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a1

array([1, 2, 3])

In [41]:
a1[0]

1

In [42]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a2[0]

array([1, 2, 3])

In [44]:
a3

array([[[ 1. ,  2. ,  3. ,  3.1],
        [ 4. ,  5. ,  6. ,  6.1],
        [ 7. ,  8. ,  9. ,  9.1]],

       [[10. , 11. , 12. , 12.1],
        [13. , 14. , 15. , 15.1],
        [16. , 17. , 18. , 18.1]]])

In [45]:
a3[0]

array([[1. , 2. , 3. , 3.1],
       [4. , 5. , 6. , 6.1],
       [7. , 8. , 9. , 9.1]])

In [57]:
a3[:2,:2,:3]

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[10., 11., 12.],
        [13., 14., 15.]]])

In [58]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [59]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [60]:
## Lấy 4 số đầu tiên của mảng
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

In [61]:
## Lấy 1 số đầu tiên của mảng
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

# Manipulating Arrays

In [62]:
a1

array([1, 2, 3])

In [65]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [66]:
a1 + ones

array([2., 3., 4.])

In [67]:
a1 - ones

array([0., 1., 2.])

In [68]:
a1 * ones

array([1., 2., 3.])

In [69]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [72]:
a2 * a1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [73]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
a3

array([[[ 1. ,  2. ,  3. ,  3.1],
        [ 4. ,  5. ,  6. ,  6.1],
        [ 7. ,  8. ,  9. ,  9.1]],

       [[10. , 11. , 12. , 12.1],
        [13. , 14. , 15. , 15.1],
        [16. , 17. , 18. , 18.1]]])

In [75]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,4) 

In [77]:
# How can you reshape a2 to be compatible with a3?
a3_reshape = np.reshape(a3,(2,3))

ValueError: cannot reshape array of size 24 into shape (2,3)

In [82]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
a1

array([1, 2, 3])

In [78]:
a1 / ones

array([1., 2., 3.])

In [79]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [84]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]], dtype=int32)

In [87]:
a2 **2 # Lũy thừa 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [88]:
np.square(a2) # Lũy thừa 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [89]:
np.add(a1,ones) # Cộng 2 matrix

array([2., 3., 4.])

In [90]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [91]:
np.exp(a1) #e^x

array([ 2.71828183,  7.3890561 , 20.08553692])

In [92]:
np.log(a1) #ln

array([0.        , 0.69314718, 1.09861229])

# Aggregation (tập hợp)

In [94]:
listy_list = [1,2,3]
type(listy_list)

list

In [95]:
sum(listy_list)

6

In [96]:
a1

array([1, 2, 3])

In [97]:
sum(a1)

6

In [98]:
np.sum(a1)

6

### Use Python's method `(sum())` on Python datatypes and use NumPy's methods on NumPy arrays `(np.sum())`

In [101]:
#Creative a massive NumPy array
massive_array = np.random.random(10000)
massive_array[:10]

array([0.98424673, 0.60166059, 0.51518261, 0.46006105, 0.7150486 ,
       0.59981275, 0.76381228, 0.72683636, 0.73356772, 0.5818986 ])

In [102]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) #NumPy's sum()

410 µs ± 18.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
3.51 µs ± 18.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [103]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
np.mean(a2) #(1+2+3+4+5+6)/6

3.5

In [106]:
np.max(a2)

6

In [107]:
np.min(a2)

1

In [109]:
np.std(a2) #Standard Deviation - độ lệch chuẩn

1.707825127659933

In [110]:
np.var(a2)

2.9166666666666665

In [111]:
# Standard deviation = squareroot of  varience
np.sqrt(np.var(a2))

1.707825127659933

# Demo of std and var

In [112]:
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [113]:
np.var(high_var_array),np.var(low_var_array)

(4296133.472222221, 8.0)