In [1]:
import numpy as np

# DataTypes & Attribute

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3],
               [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a3 = np.array([[[1,2,3,3.1],
                [4,5,6,6.1],
                [7,8,9,9.1]],
               [[10,11,12,12.1],
                [13,14,15,15.1],
                [16,17,18,18.1]]
              ])
a3

array([[[ 1. ,  2. ,  3. ,  3.1],
        [ 4. ,  5. ,  6. ,  6.1],
        [ 7. ,  8. ,  9. ,  9.1]],

       [[10. , 11. , 12. , 12.1],
        [13. , 14. , 15. , 15.1],
        [16. , 17. , 18. , 18.1]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 4)

In [16]:
#  function return the number of dimensions of an array
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('float64'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 24)

# Create a DataFrame from Numpy array

In [19]:
import pandas as pd

In [23]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# Creating arrays

In [24]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [25]:
sample_array.dtype

dtype('int32')

In [26]:
ones = np.ones((2,3)) #Return a new array of given shape and type, filled with ones.
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
ones.dtype

dtype('float64')

In [29]:
zeros = np.zeros((2,3)) #Return a new array of given shape and type, filled with zeros.
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])